# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBQ1YhEdZ8QwWWxk-yQy35jS3hM5OKst
"""

!pip install streamlit
!pip install yfinance

import streamlit as st
import yfinance as yf

#st.sct_page_config(
#    page_title = "PAINEL DA B3",
#    layout = "wide",
#)

st.header("**PAINEL DE PRECOS E DIVIDENDOS DE ACOES DA B3**")

ticker = st.text_input("Digite o ticker da acao","BBAS3")
empresa = yf.Ticker(f"{ticker}.SA")

tickerDF = empresa.history(period ="1d",
                           start = "2014-01-01",
                           end = "2025-10-30")

col1, col2, col3 = st.colums([1,1,1])

with col1:
  st.write(f"**Empresa:** {empresa.info['longName']}")
with col2:
  st.write(f"**Setor:** {empresa.info['industry']}")
with col1:
  st.write(f"**Preço Atual:** {empresa.info['currentPrice']}")

st.line_chart(tickerDF.Close)
st.bar_chart(tickerDF.Dividends)